### ISSUE TITLE
error compiling

### ISSUE THREAD

**Issue by kubrastain** [shanapu/MathQuiz#1]
Hi Thomas! I am a big fan of their works, besides good, they are free (a combination more than perfect haha).

Checking your repositories, I saw that there is this plugin, which I believe would be very useful in my jailbreak!

When trying to compile, I had the following error: [http://prntscr.com/m8yqbm
![download](https://user-images.githubusercontent.com/25697393/51397438-66de5780-1b28-11e9-9f1c-b07a30e9c3bc.jpg)
](url)

How can I solve?

**Comment by shanapu** [comment]
Thank you =)

I havn't touched this plugin for long time. 
It still use the old [simple chat processor (redux)](https://bitbucket.org/minimoney1/simple-chat-processor/). 
I should update it to use the newer more recommend [chat-processor](https://github.com/Drixevel/Chat-Processor). Which is also used by MyJailbreak.

Anyway you can find the right scp.inc file for proper compile here:
https://bitbucket.org/minimoney1/simple-chat-processor/raw/949b2e410fa5571fff216767a7a8093cedebafcb/scripting/include/scp.inc

**Comment by shanapu** [comment]
I added the correct scp.inc to repo ed84596e3d889b90b26ed5de2751741650b46fb5 and also added a precompiled binary.

Also I open a [new branch](https://github.com/shanapu/MathQuiz/tree/chat-processor) for the chat-processor.
